config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "schedules#index"

  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :schedules
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_schedule, only: %i[ show edit update destroy ]

  # GET /schedules or /schedules.json
  def index
    @schedules = Schedule.where(user: current_user)
  end

  # GET /schedules/1 or /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules or /schedules.json
  def create
    @schedule = current_user.schedules.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to schedule_url(@schedule), notice: "O agendamento foi criado com sucesso." }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1 or /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to schedule_url(@schedule), notice: "O agendamento foi editado com sucesso." }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1 or /schedules/1.json
  def destroy
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url, notice: "O agendamento foi deletado." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def schedule_params
      params.require(:schedule).permit(:user_id, :begin_time, :end_time, :subject, :description)
    end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end
  
    self.responder = Responder
    respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Já Marquei</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Início</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Agendar aula', new_schedule_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/">Histórico de aulas</a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to('Sair', destroy_user_session_path, data: { turbo_method: :delete } , class: 'nav-link') %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to('Entrar', new_user_session_path, class: 'nav-link') %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agenda</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%=render "layouts/navbar"%>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/schedules/_form.html.erb
<%= form_with(model: schedule) do |form| %>
  <% if schedule.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
        <% schedule.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <label for="begin_time", style="display:block;">Início</label>
    <%= form.datetime_field :begin_time %>
  </div>

  <div>
    <label for="end_time", style="display:block;">Fim</label>
    <%= form.datetime_field :end_time %>
  </div>

  <div>
    <label for="subject", style="display:block;">Tema da Reunião</label>
    <%= form.text_field :subject %>
  </div>

  <div>
    <label for="description", style="display:block;">Descrição</label>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit "Confirmar", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/schedules/_schedule.html.erb
<tbody>
  <tr>
    <td><%= schedule.begin_time&.strftime("%H:%M %d/%m/%y") %></th>
    <td><%= schedule.end_time&.strftime("%H:%M %d/%m/%y") %></td>
    <td><%= schedule.subject %></td>
    <td><%= schedule.description %></td>
    <td><%= link_to "Mostrar Agendamento", schedule %></td>
  </tr>
</tbody>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render "form", schedule: @schedule %>

<br>

<div>
  <%= link_to "Mostrar esse agendamento", @schedule %> |
  <%= link_to "Voltar para agenda", schedules_path %>
</div>

app/views/schedules/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Olá</h1>

<h5>Sua agenda</h5>

<div id="schedules">
<table class="table">
  <thead>
    <tr>
      <th scope="col">Início</th>
      <th scope="col">Fim</th>
      <th scope="col">Temas da reunião</th>
      <th scope="col">Descrição</th>
    </tr>
  </thead>
  <% @schedules.each do |schedule| %>
    <%= render schedule %>
  <% end %>
</table>
</div>

<%= link_to "Novo agendamento", new_schedule_path %>

app/views/schedules/new.html.erb
<h1 class='pt-3'>Novo agendamento</h1>

<div class='container'>
  <%= render "form", schedule: @schedule %>
</div>

<br>

<div>
  <%= link_to "Voltar para o início", schedules_path %>
</div>

app/views/schedules/show.html.erb
<p style="color: green"><%= notice %></p>


<table class="table">
  <thead>
    <tr>
      <th scope="col">Início</th>
      <th scope="col">Fim</th>
      <th scope="col">Temas da reunião</th>
      <th scope="col">Descrição</th>
    </tr>
  </thead>
  <%= render @schedule %>
</table>
</div>

<div class='py-3'>
  <%= link_to "Editar agendamento ", edit_schedule_path(@schedule) %> |
  <%= link_to "Voltar para agenda", schedules_path %>
</div>

<%= button_to "Deletar agendamento", @schedule, method: :delete, class: "btn btn-danger" %>